# Generated by Django 3.2.9 on 2021-11-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('data', models.TextField()),
            ],
        ),
    ]
